#!/usr/bin/env bun
/**
 * Codegen: embed the OpenResty .lua scripts into a TS module as base64.
 *
 * WHY: the compiled desktop binary (`bun build --compile`) and other bundlers
 * can't resolve a module-relative `lua/` dir, and a staged dir depends on env
 * wiring that has silently broken in the field — a missing rules_guard.lua once
 * 500'd every customer site (every managed vhost's `access_by_lua_file` points
 * at a file that wasn't there). Embedding the scripts as base64 string
 * constants makes them ATOMIC: they travel inside the JS across tsc / esbuild /
 * bun --compile / Docker with no path to lose — the same way MANAGEMENT_BLOCK /
 * DEFAULT_BLOCK are inline constants in openresty-lua.ts. Base64 (not raw
 * template literals) because several scripts contain backticks and ${...} that
 * would break a raw literal.
 *
 * Run `bun run embed:lua` (in packages/adapters) after editing any lua/*.lua.
 * The lua-embedded.test.ts guard fails CI if this output drifts from source.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const LUA_DIR = join(HERE, "..", "src", "infra", "lua");
const OUT = join(HERE, "..", "src", "infra", "lua-embedded.ts");

/** Build the generated module text from the current lua/*.lua source. Exported
 *  so the drift test can compare against the committed file without shelling. */
export function generateEmbeddedModule(): string {
  const files = readdirSync(LUA_DIR)
    .filter((f) => f.endsWith(".lua"))
    .sort();

  const entries = files.map((f) => {
    const b64 = readFileSync(join(LUA_DIR, f)).toString("base64");
    return `  ${JSON.stringify(f)}: ${JSON.stringify(b64)},`;
  });

  return `// GENERATED by scripts/embed-lua.ts — DO NOT EDIT BY HAND.
// Run \`bun run embed:lua\` (in packages/adapters) after editing any lua/*.lua.
//
// The OpenResty Lua scripts, base64-encoded and embedded so they travel INSIDE
// the JS across every toolchain (tsc / esbuild / bun --compile / Docker) with
// no filesystem path to lose. A script missing here would 500 every managed
// vhost, so the source of truth is src/infra/lua/*.lua and this file mirrors it
// (lua-embedded.test.ts fails on drift). Decode with Buffer.from(v,"base64").
export const EMBEDDED_LUA: Record<string, string> = {
${entries.join("\n")}
};
`;
}

// Direct invocation (`bun scripts/embed-lua.ts`) writes the file. When imported
// by the test we only use generateEmbeddedModule() and skip the write.
if (import.meta.main) {
  const body = generateEmbeddedModule();
  writeFileSync(OUT, body);
  const count = body.match(/\.lua"/g)?.length ?? 0;
  console.log(`[embed-lua] wrote ${count} scripts → ${OUT}`);
}
