#!/usr/bin/env bun
/**
 * Codegen: embed the native-module migration catalog into a TS module as base64.
 *
 * WHY: same rationale as embed-lua.ts — the compiled binary / bundlers can't
 * resolve a module-relative catalog dir, so we bake the catalog (manifest + its
 * detached signature + every asset) as base64 constants that travel INSIDE the
 * JS. This is the OFFLINE fallback: an air-gapped instance still migrates from
 * the bundled catalog, and it runs through the same verify gate (the signature
 * is embedded too), so there is no unsigned execution path.
 *
 * Source tree: src/system/modules/catalog/<module>/
 *   catalog.json        — the manifest (signed at release time)
 *   catalog.json.sig    — detached ed25519 signature over catalog.json bytes
 *   <anything else>     — assets, keyed by path relative to the module dir
 *
 * Run `bun run embed:catalog` (in packages/adapters) after editing the catalog.
 * The catalog-embedded.test.ts guard fails CI if this output drifts from source.
 */
import { readdirSync, readFileSync, statSync, existsSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const CATALOG_DIR = join(HERE, "..", "src", "system", "modules", "catalog");
const OUT = join(HERE, "..", "src", "system", "modules", "catalog-embedded.ts");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

interface EmbeddedModule {
  manifest: string;
  sig: string;
  assets: Record<string, string>;
}

export function generateEmbeddedModule(): string {
  const modules: Record<string, EmbeddedModule> = {};

  if (existsSync(CATALOG_DIR)) {
    for (const module of readdirSync(CATALOG_DIR)) {
      const moduleDir = join(CATALOG_DIR, module);
      if (!statSync(moduleDir).isDirectory()) continue;
      const manifestPath = join(moduleDir, "catalog.json");
      if (!existsSync(manifestPath)) continue;

      const sigPath = join(moduleDir, "catalog.json.sig");
      const assets: Record<string, string> = {};
      for (const file of walk(moduleDir)) {
        const rel = relative(moduleDir, file).split("\\").join("/");
        if (rel === "catalog.json" || rel === "catalog.json.sig") continue;
        assets[rel] = readFileSync(file).toString("base64");
      }
      modules[module] = {
        manifest: readFileSync(manifestPath).toString("base64"),
        sig: existsSync(sigPath) ? readFileSync(sigPath).toString("base64") : "",
        assets,
      };
    }
  }

  const body = Object.entries(modules)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([mod, m]) => {
      const assetEntries = Object.entries(m.assets)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => `      ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
        .join("\n");
      return (
        `  ${JSON.stringify(mod)}: {\n` +
        `    manifest: ${JSON.stringify(m.manifest)},\n` +
        `    sig: ${JSON.stringify(m.sig)},\n` +
        `    assets: {\n${assetEntries}\n    },\n` +
        `  },`
      );
    })
    .join("\n");

  return `// GENERATED by scripts/embed-catalog.ts — DO NOT EDIT BY HAND.
// Run \`bun run embed:catalog\` (in packages/adapters) after editing the catalog
// under src/system/modules/catalog/. Base64-embedded so the bundled fallback
// catalog travels inside the JS across every toolchain. It is signature+hash
// verified at load time exactly like the remote catalog (catalog-source.ts).
export interface EmbeddedCatalogEntry {
  /** base64 of catalog.json bytes. */
  manifest: string;
  /** base64 of the detached ed25519 signature ("" until the catalog is signed). */
  sig: string;
  /** asset key (path relative to the module dir) → base64 bytes. */
  assets: Record<string, string>;
}

export const EMBEDDED_CATALOG: Record<string, EmbeddedCatalogEntry> = {
${body}
};
`;
}

if (import.meta.main) {
  const body = generateEmbeddedModule();
  writeFileSync(OUT, body);
  const count = body.match(/^ {2}"[^"]+": \{$/gm)?.length ?? 0;
  console.log(`[embed-catalog] wrote ${count} module(s) → ${OUT}`);
}
