import { createAuthClient } from "better-auth/react";
import { organizationClient } from "better-auth/client/plugins";
import { getAuthBaseUrl } from "@/lib/api/urls";

/**
 * API base URL - auth requests go directly to the selected API origin.
 *
 * Local SaaS uses localhost:4100. Public-host dev and production use
 * api.openship.io so Better Auth can share cookies with app.openship.io.
 */
const AUTH_BASE_URL = getAuthBaseUrl();

export const authClient = createAuthClient({
  baseURL: AUTH_BASE_URL,
  fetchOptions: {
    credentials: "include",
    // Disable retry to prevent infinite loops on 429
    retry: {
      type: "linear",
      attempts: 0,
      delay: 0,
    },
  },
  plugins: [organizationClient()],
});

export const {
  signIn,
  signUp,
  signOut,
  useSession,
} = authClient;

/**
 * Email / password helpers - these are proxy-generated by Better Auth
 * when the server has emailAndPassword enabled. We access them via
 * the client object so TypeScript doesn't complain about missing
 * static properties.
 */
export const forgetPassword = (authClient as any).forgetPassword as (
  opts: { email: string; redirectTo?: string },
) => Promise<{ error?: { message?: string } }>;

export const resetPassword = (authClient as any).resetPassword as (
  opts: { newPassword: string; token?: string },
) => Promise<{ error?: { message?: string } }>;

export const sendVerificationEmail = (authClient as any).sendVerificationEmail as (
  opts: { email: string; callbackURL?: string },
) => Promise<{ error?: { message?: string } }>;

export const verifyEmail = (authClient as any).verifyEmail as (
  opts: { query: { token: string } },
) => Promise<{ error?: { message?: string } }>;
